### PR TITLE
Alternate state switching

### LINKED ISSUE #30: Quote and weather rotation does not work
https://forums.balena.io/t/inkyshot-variables-not-working/203394

### PR DESCRIPTION
**Pull request by manuelemac**
fixes #30

### CODE REVIEW

**Comment by catt-tung** [comment]
> fixes #30

Hi there @manuelemac thanks for the contribution! Please would you be able to update your commit message suitable for the change log and add to the change-type line? The guidelines are -

Contributing & Commit structure
When submitting a pull request, please use the guidance outlined below.
Each commit message should consist of a body and a footer, structured in the following format:
`<scope (optional)>: <subject (mandatory)>
--BLANK LINK--
(optional) <body>
--BLANK LINE--
(optional) Connects-to: #issue-number
(mandatory) Change-type: major | minor | patch
(optional) Signed-off-by: Foo Bar <foobar@balena.io>`

**Comment by manuelemac** [comment]
Hi!
Sorry for the incomplete commit, I had a memory about _only_ #issue n°
mandatory.
I'll soon update.

**Comment by gelbal** [comment]
Hi @manuelemac, thank you for your contribution. I'm testing this and it does not fix the issue. Investigating this further, I believe there is a deeper flaw in the original code logic. 

So `cron` job (which is the process that runs the update script) never reads the new environment variable set by the python script and it always falls back to the original environment variable set on the dashboard. I realized that a process can only update the environment for itself and its children, the python script's process has no power over the `cron` that executes it, therefore `NEXT_DISPLAY` is never updated.

I'm working on a fix to use device tags instead of environment variables.

**Comment by manuelemac** [comment]
Ok. 
unfortunately I tested the code skipping the _cron_ to save time, but wasn't a good idea.

**Pull request closed without merging**
