### PR TITLE
Add quote category variable

### PR DESCRIPTION
**Pull request by SamEureka**
Hello! 

I wanted to change the quote category to `love` for my inkyshot project and saw that there was an open issue to add the feature. So here is my very first open source PR contribution! 

Regards,
//Sam

resolves balenalabs/inkyshot#18

### CODE REVIEW

**Comment by chrisys** [comment]
@SamEureka this is awesome! Thanks for digging in and contributing 👍 

What we need to do to get the CI to test and approve your changes is update the commit message for one of the commits in each PR. We need to add these notes to this repo (that's my bad for not doing this), but if you can update one of the commits in each PR so it follows this format you should see the checks start passing:

Screenshot 2020-09-29 at 10 59 46

You can take a look at any of my historical commits to see what it looks like:

Screenshot 2020-09-29 at 11 02 42

Both of your PRs add functionality so please mark them as 'minor' changes. LMK if you need any more help with this, and thanks again for the contribution! I'll definitely be updating my devices to get these changes :)

**Comment by SamEureka** [comment]
@chrisys I've added the commit messages for CI. Hopefully I did it right. Multi-line commit messages are new to me. I also added the commit structure guidance to the bottom of the README.md.

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@SamEureka that looks great now and thanks for adding the information to the readme too! Is there any chance you can squash these 3 commits? The reason being is that each commit gets added to the changelog for the project, so we don't want to add an entry that says 'added commit for CI'. If you add the signoff line too it will credit you in the changelog as well, not just in the git history. As an example you could squash all three into 'Add quote category variable'. 

It looks like the test build is failing now but I don't think that's due to any of your changes - I'll look into this separately.

**Comment by SamEureka** [comment]
Commits have been squashed 👊🏻

**Review by chrisys — APPROVED** [review]

**Comment by chrisys** [comment]
@SamEureka merged! thanks for the contribution!

**Comment by huckleberry914** [comment]
Amazing!! Can't wait until I'm better at coding so I can contribute myself...but I'm so happy to see that this got implemented. Thank you so much for your contribution!

**Pull request merged**
