### PR TITLE
Fixed BLACK & WHITE pixels for Waveshare Weather Icon

### PR DESCRIPTION
**Pull request by louispires**
Fixes issue with Waveshare Weather Icon not displaying

Connects-to: #48
Change-type: patch

### CODE REVIEW

**Review by chrisys — APPROVED** [review]

**Comment by chrisys** [comment]
@louispires thanks for the contribution!

**Comment by louispires** [comment]
No problem @chrisys - Kindly also look at PR #50 #51 #52

**Comment by chrisys** [comment]
Sure, will do. We're looking into why that build check is failing as well; it shouldn't be. After that this will merge automatically 👍

**Comment by chrisys** [comment]
@balena-ci rebase

**Comment by chrisys** [comment]
@balena-ci retest

**Pull request merged**
