### PR TITLE
patch: Weather image inverted

### PR DESCRIPTION
**Pull request by louispires**
Weather Icon Inverted

Set the `WEATHER_INVERT` environment variable which will invert the Icon being generated and thus give it a different look

Before:
image

After:
image

Change-type: minor

### CODE REVIEW

**Comment by chrisys** [comment]
@louispires I've tested this but the invert functionality doesn't work on the Inkyphat screen, the image just disappears. I've attached a photo below of what both displays look like without setting the invert variable - perhaps we should aim for both to behave in the same way before introducing the invert function?

Screenshot 2021-06-11 at 13 30 29

**Comment by louispires** [comment]
Agreed @chrisys - or maybe just make the Invert possible for the `WAVESHARE` screen only.

As the Image already looks really good on the Inkyphat screen from your photo.

**Comment by chrisys** [comment]
@balena-ci rebase

**Review by chrisys — APPROVED** [review]

**Comment by chrisys** [comment]
@balena-ci retest

**Pull request merged**
